name: miyaa
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  background_location: ^0.13.0
  cached_network_image: ^3.4.1
  chat_bubbles: ^1.6.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.3
  flutter_local_notifications: ^18.0.0
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  geolocator: ^13.0.1
  go_router: ^14.4.1
  image_picker: ^1.1.2
  is_first_run: ^1.0.0
  jwt_decoder: ^2.0.1
  lottie: ^3.1.3
  responsive_builder: ^0.7.1
  shared_preferences: ^2.3.2
  simple_ripple_animation: ^0.0.9
  socket_io_client: ^3.0.1
  theme_manager: ^2.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/lottie/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
